name: libft workflow

on:
  push:
      branches:
        - master

jobs:
  norminette:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies 
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install norminette 
      - name: Test with norminette
        run: norminette
  build:
    name: build
    needs: norminette
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make